"""Startup seed: Google Sheets Analyst agent.

Provisions a pre-configured *Google Sheets Analyst* agent on first run.
The agent reads data from a Google Spreadsheet, performs analysis based on
a task requirement, and writes structured insights into a new sheet tab.

Usage (via the chat or workflow interface)
------------------------------------------
Send a task to the agent in the following format::

    SHEETID: <your-spreadsheet-id>
    TASKREQUIREMENT: <what you want to analyse or answer>

The agent will:
1. Inspect the spreadsheet structure (``get_metadata``, ``list_sheets``).
2. Read relevant data (``get_values``).
3. Analyse the data against the task requirement.
4. Create a new output sheet tab (``create_sheet``).
5. Write a structured report with headers, findings, and a summary
   (``write_values``).

The seed is idempotent: if an agent named *"Google Sheets Analyst"* already
exists in the database the function returns without making any changes.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

_AGENT_NAME = "Google Sheets Analyst"

_SYSTEM_PROMPT = """You are a **Google Sheets Analyst** — an expert data analyst whose job is to
read data from Google Sheets, perform thorough analysis, and write structured
insights back into the same spreadsheet.

## Input format
Every task will contain two fields:
- **SHEETID** – the Google Spreadsheet ID (the alphanumeric string in the URL).
- **TASKREQUIREMENT** – what the user wants to know, analyse, or summarise.

## Workflow — follow these steps precisely

### 1. Discover the spreadsheet structure
- Call `get_metadata` with the SHEETID to learn the spreadsheet title and
  available sheet tabs.
- If there are multiple tabs, call `list_sheets` and decide which tabs contain
  the data relevant to the task.

### 2. Read the data
- Call `get_values` for each relevant tab/range.
- Use a sufficiently large `max_rows` (e.g. 500–2000) to capture the full
  dataset.
- If you need multiple ranges, call `get_values` multiple times.
- Always read the header row first to understand column meanings.

### 3. Analyse
- Examine the data thoroughly.
- Answer every aspect of the TASKREQUIREMENT with supporting evidence from
  the data (numbers, percentages, comparisons, trends, anomalies).
- Prepare your findings as a structured report with:
  - An **Executive Summary** (3–5 bullet points)
  - **Key Findings** (detailed per-question answers with data citations)
  - **Recommendations** (actionable next steps, if applicable)
  - A **Data Overview** row (column count, row count, date range if applicable)

### 4. Create the output sheet
- Pick a concise tab title that describes the analysis, e.g.
  `"Analysis - Sales Q1"` or `"Insights - Churn"`.
- Call `create_sheet` with that title.
  - If creation fails because a sheet with that name already exists, append
    a timestamp suffix (e.g. `"Analysis - Sales Q1 (2)"`) and try again.

### 5. Write the report
Format the output as rows of cells (a 2-D list) and write them with
`write_values`.  Structure:

| Row | Content |
|-----|---------|
| 1   | Title: "Analysis Report — <task summary>" |
| 2   | "Generated by: Google Sheets Analyst" |
| 3   | Empty |
| 4   | "EXECUTIVE SUMMARY" |
| 5-N | Bullet point rows (one per row, column A) |
| N+1 | Empty |
| N+2 | "KEY FINDINGS" |
| ...  | One finding per row, using columns A (label) and B (value/detail) |
| ... | Empty |
| ... | "RECOMMENDATIONS" |
| ... | One recommendation per row |
| ... | Empty |
| ... | "DATA OVERVIEW" |
| ... | Row count, column count, sheets read, etc. |

Use the range `"<NewSheetTitle>!A1"` as the starting cell for `write_values`.

### Rules
- Never modify existing sheets or data — only write to the newly created tab.
- Always confirm the sheet was created before writing.
- If any tool returns an `"error"` key, report it clearly and stop — do not
  guess or fabricate data.
- Keep cell values as plain strings (no formulas unless the user explicitly
  requests them).
- Be thorough: a good report should have 20–60 rows of content.
"""


async def seed_google_sheets_analyst() -> None:
    """Provision the Google Sheets Analyst agent if it does not yet exist.

    Must be called *after* ``init_db()`` and
    ``plugin_loader.load_plugins_from_config()`` have completed so that both
    Beanie and the ``google_sheets`` CustomTool document are available.
    """
    from app.models.agent import Agent  # noqa: PLC0415
    from app.models.custom_tool import CustomTool  # noqa: PLC0415

    # ── Idempotency check ──────────────────────────────────────────────
    existing = await Agent.find_one({"name": _AGENT_NAME})
    if existing is not None:
        logger.info("Seed: '%s' agent already exists — skipping.", _AGENT_NAME)
        return

    # ── Resolve the google_sheets plugin tool ID ───────────────────────
    tool = await CustomTool.find_one({"name": "google_sheets"})
    if tool is None:
        logger.warning(
            "Seed: 'google_sheets' plugin not found in database. "
            "Make sure 'google_sheets' is enabled in plugins.yaml and that "
            "plugin_loader has run before this seed. Skipping agent creation."
        )
        return

    tool_id = str(tool.id)

    # ── Create the agent ───────────────────────────────────────────────
    agent = Agent(
        name=_AGENT_NAME,
        description=(
            "Analyst agent that reads data from any Google Spreadsheet and writes "
            "structured insights into a new sheet tab. "
            "Input: SHEETID and TASKREQUIREMENT."
        ),
        system_prompt=_SYSTEM_PROMPT,
        custom_tool_ids=[tool_id],
        builtin_tools=[],
    )
    await agent.insert()
    logger.info("Seed: Created '%s' agent (id=%s) with tool '%s'.", _AGENT_NAME, agent.id, tool_id)
